name: Run Python Script and Create PR

on:
  push:
    branches:
      - main
    paths:
      - assets/queries/**

jobs:
  run-script-and-pr:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: auto-gen-${{ github.run_id }} 


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: pwd
        run: |
          ls
          ls documentation

      - name: Checkout to new branch
        run: git checkout -b ${{ env.BRANCH_NAME }}

      - name: Run Python script
        run: python documentation/local_gen.py assets/queries/ --resources-json "documentation/resources.json"

      - name: Commit changesMore actions
        uses: iarekylew00t/verified-bot-commit@v1
        with:
          message: 'feat: Some changes'
          files: |
            **
          ref: "heads/${{ env.BRANCH_NAME }}"
      
      - name: Push branch
        run: git push origin ${{ env.BRANCH_NAME }}

      - name: Create pull request and get URL
        id: create_pr
        run: |
          PR_URL=$(gh pr create -B main -H "${{ env.BRANCH_NAME }}" --title 'Update docs' --body 'Created by Github action')
          echo "pr_url=$PR_URL" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send GitHub Action data to a Slack workflow
        uses: slackapi/slack-github-action@v2.1.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: |
            {
              "PR_url": "${{ steps.create_pr.outputs.pr_url }}"
            }
